apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: guestbook-dev

namespace: guestbook-dev

resources:
- ../../base

labels:
- pairs:
    app.kubernetes.io/environment: dev

namePrefix: dev-

replicas:
- name: guestbook-ui
  count: 1

patches:
- target:
    kind: Deployment
    name: guestbook-ui
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "32Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "25m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "64Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "50m" 