apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: guestbook
          image: gcr.io/google-samples/gb-frontend:v5